### ISSUE TITLE
[Bug] SSD state reported as a string instead of an int

### ISSUE THREAD

**Issue by janusn** [tomaae/homeassistant-truenas#189]
## Describe the issue

The state of a SSD drive is a string instead of an int as show in the following code in template:
```
{{ (states.sensor
    | selectattr('entity_id', 'match', 'sensor.truenas_disks_nvme0n1')
    | map(attribute='state')
    | list
    | first
    ) is string
}}
```
Result:
```
True
```

In contrast to the state of a HDD as illustrated in the following code in template:
```
{{ (states.sensor
    | selectattr('entity_id', 'match', 'sensor.truenas_disks_sda')
    | map(attribute='state')
    | list
    | first
    ) is number
}}
```
Result:
```
True
```
It makes the card entity_filter failed to work with SSD as illustrated in the following code:
```
type: entity-filter
show_empty: false
entities:
  - sensor.truenas_disks_nvme0n1
conditions:
  - condition: numeric_state
    below: 5
card:
  type: entities
```

## How to reproduce the issue

Install and configure [TrueNAS integration](https://community.home-assistant.io/t/truenas-integration/410431)
type the following code in Developer tools->TEMPLATE
```
{{ (states.sensor
    | selectattr('entity_id', 'match', 'sensor.truenas_disks_nvme0n1')
    | map(attribute='state')
    | list
    | first
    ) is number
}}
```

## Expected behavior

The Result should show 'True'

## Software versions

 - Home Assistant version:  HA 2024.11.3
 - TrueNAS integration version:  v1.3.1
 - TrueNAS version:  SCALE ElectricEel-24.10.0.2
