### ISSUE TITLE
[Question] Documentation on how to control e.g. VMs

### ISSUE THREAD

**Issue by mamama1** [tomaae/homeassistant-truenas#214]
Hello,

docs say this extension can control VM state (i.e. power on, shut down, I assume). But apart from "available through services" it doesn't elaborate on how to actually configure this. Unfortunately, I have absolutely no idea how I'd be able to achieve my goal of having on/off toggles for each of my VMs (or at least push buttons) to start or shut them down from home assistant.

Help would be greatly appreciated!

**Comment by tomaae** [comment]
There is nothing to configure, you can use them as any other HA services.
If you want to have them as buttons, you can create one like this:
```
template:
  - button:
    - name: Start PBS VM
      icon: mdi:play-circle-outline
      press:
        action: truenas.vm_start
        target:
          entity_id: binary_sensor.truenas_vms_pbs
```
You can create switch too, just lookup template switch.

BTW, "services" has been recently renamed to "actions" in HA, just to avoid confusion.
