### ISSUE TITLE
[Feature] Alerts 

### ISSUE THREAD

**Issue by reven** [tomaae/homeassistant-truenas#53]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

It would be great to have notifications (errors, task completion, etc). They could be informative and also be the basis for automations.

## Describe alternatives you've considered

I've used a rest sensor for alerts but it often gives errors as the api returns empty json if there are none. I know that the api exposes notification dismissal too, but not sure how that would be implemented.

**Comment by tomaae** [comment]
can you give me endpoint which you used?

**Comment by reven** [comment]
Of course!

The main alert endpoint is /api/v2.0/alert/list (GET). To dismiss an alert the endpoint is /api/v2.0/alert/dismiss (POST).

The rest sensor I had is below. As I said this gives errors in HA because if there are no alerts the json returned is []. I don't know if this is expected. The conditional tries to catch the exception, but I wasn't able to find a way to make the attribute loading conditional, which I guess is what fails because the Indexes don't exist if it's empty.

Hope this helps.

```
# Alerts. Error if response is empty.
- platform: rest
  name: tn_alert_level
  resource: http://___address___/api/v2.0/alert/list
  headers:
    Authorization: !secret tn_api_key
    Content-Type: application/json
    User-Agent: Home Assistant
  scan_interval: 300
  json_attributes:
    - level
    - formatted
  value_template: >
    {% if value_json is defined %}
      {{ value_json[0].level }}
    {% else %}
      {{ "None" }}
    {% endif %}
- platform: template
  sensors:
    ## Alert message
    tn_alert_message:
      unique_id: 6c8fd927-e198-4f0e-b67e-2d42e7c9ed04
      friendly_name: "Alert Message"
      value_template: "{{ state_attr('sensor.tn_alert_level', 'formatted') }}"
```
