### ISSUE TITLE
[Question] bge0 RX/TX in (nearly) realtime possible?

### ISSUE THREAD

**Issue by daloki83** [tomaae/homeassistant-truenas#84]
Hi,
i just want to use these two sensors:
```
sensor.truenas_system_bge0_rx
sensor.truenas_system_bge0_tx
```
So i disabled everything else in Home Assistant and created a Helper and a Template sensor to calculate it from KiB in MBit/s. 
```
template:
  sensor:
    - name: Server_Netzwerk_Speed
      icon: mdi:currency-usd
      state: >-
        {{ (states('sensor.truenas_kib') | int * 0.00102459) | round(2) }} MBit/s
```

So far everything is working well. But the update times are way high for my project. Is there any way to improve this? Could i change something in your intergration?
